// Lightweight notification helper.
// True background push requires VAPID + service worker + a push server.
// This implementation handles:
//  - permission request UX
//  - foreground notifications via the Notification API
//  - scheduled in-tab reminders (work as long as the tab is open)
// Smart reminder content is generated by reminders.ts.

const PERM_KEY = "forge:notify";

export type NotifyPermission = "default" | "granted" | "denied" | "unsupported";

export function getNotifyPermission(): NotifyPermission {
  if (typeof window === "undefined" || !("Notification" in window)) return "unsupported";
  return Notification.permission as NotifyPermission;
}

export function notificationsEnabled() {
  if (typeof localStorage === "undefined") return false;
  return localStorage.getItem(PERM_KEY) === "1" && getNotifyPermission() === "granted";
}

export function setNotificationsEnabled(v: boolean) {
  localStorage.setItem(PERM_KEY, v ? "1" : "0");
}

export async function requestNotificationPermission(): Promise<NotifyPermission> {
  if (typeof window === "undefined" || !("Notification" in window)) return "unsupported";
  if (Notification.permission === "granted") {
    setNotificationsEnabled(true);
    return "granted";
  }
  if (Notification.permission === "denied") return "denied";
  const res = await Notification.requestPermission();
  setNotificationsEnabled(res === "granted");
  return res as NotifyPermission;
}

export function fireNotification(title: string, body: string) {
  if (!notificationsEnabled()) return;
  try {
    new Notification(title, { body, icon: "/app-icon-192.png", tag: "forge-reminder" });
  } catch {
    /* ignore */
  }
}

/* ---------- Install / platform awareness (mobile notification support) ---------- */

/** True when running as an installed app (home-screen / standalone window). */
export function isStandalone() {
  if (typeof window === "undefined") return false;
  return (
    window.matchMedia?.("(display-mode: standalone)").matches ||
    // iOS Safari
    (window.navigator as unknown as { standalone?: boolean }).standalone === true
  );
}

export function isIOS() {
  if (typeof navigator === "undefined") return false;
  return (
    /iPad|iPhone|iPod/.test(navigator.userAgent) ||
    (navigator.platform === "MacIntel" && (navigator as unknown as { maxTouchPoints: number }).maxTouchPoints > 1)
  );
}

export function isMobile() {
  if (typeof navigator === "undefined") return false;
  return /Android|iPad|iPhone|iPod|Mobile/i.test(navigator.userAgent);
}

/**
 * Plain-language explanation of what this device can actually do with
 * reminders, so the UI never promises something the browser won't deliver.
 */
export function notifySupportNote(): string | null {
  if (getNotifyPermission() === "unsupported") {
    if (isIOS() && !isStandalone()) {
      return "On iPhone, reminders only work after you add Forge to your Home Screen.";
    }
    return "This browser doesn't support notifications.";
  }
  if (isIOS() && !isStandalone()) {
    return "Add Forge to your Home Screen for reliable iPhone reminders.";
  }
  if (isMobile() && !isStandalone()) {
    return "Install Forge to your home screen so reminders keep working.";
  }
  return null;
}
