// Lightweight notification helper.
// True background push requires VAPID + service worker + a push server.
// This implementation handles:
//  - permission request UX
//  - foreground notifications via the Notification API
//  - scheduled in-tab reminders (work as long as the tab is open)
// Smart reminder content is generated by reminders.ts.

const PERM_KEY = "forge:notify";

export type NotifyPermission = "default" | "granted" | "denied" | "unsupported";

export function getNotifyPermission(): NotifyPermission {
  if (typeof window === "undefined" || !("Notification" in window)) return "unsupported";
  return Notification.permission as NotifyPermission;
}

export function notificationsEnabled() {
  if (typeof localStorage === "undefined") return false;
  return localStorage.getItem(PERM_KEY) === "1" && getNotifyPermission() === "granted";
}

export function setNotificationsEnabled(v: boolean) {
  localStorage.setItem(PERM_KEY, v ? "1" : "0");
}

export async function requestNotificationPermission(): Promise<NotifyPermission> {
  if (typeof window === "undefined" || !("Notification" in window)) return "unsupported";
  if (Notification.permission === "granted") {
    setNotificationsEnabled(true);
    return "granted";
  }
  if (Notification.permission === "denied") return "denied";
  const res = await Notification.requestPermission();
  setNotificationsEnabled(res === "granted");
  return res as NotifyPermission;
}

export function fireNotification(title: string, body: string) {
  if (!notificationsEnabled()) return;
  try {
    new Notification(title, { body, icon: "/favicon.ico", tag: "forge-reminder" });
  } catch {
    /* ignore */
  }
}
