/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppPlannerRouteImport } from './routes/_app.planner'
import { Route as AppPartnersRouteImport } from './routes/_app.partners'
import { Route as AppModerationRouteImport } from './routes/_app.moderation'
import { Route as AppJournalRouteImport } from './routes/_app.journal'
import { Route as AppHabitsRouteImport } from './routes/_app.habits'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppCommunitiesIndexRouteImport } from './routes/_app.communities.index'
import { Route as AppChallengesIndexRouteImport } from './routes/_app.challenges.index'
import { Route as AppCommunitiesNewRouteImport } from './routes/_app.communities.new'
import { Route as AppCommunitiesSlugRouteImport } from './routes/_app.communities.$slug'
import { Route as AppChallengesNewRouteImport } from './routes/_app.challenges.new'
import { Route as AppChallengesIdRouteImport } from './routes/_app.challenges.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppPlannerRoute = AppPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => AppRoute,
} as any)
const AppPartnersRoute = AppPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AppRoute,
} as any)
const AppModerationRoute = AppModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AppRoute,
} as any)
const AppJournalRoute = AppJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => AppRoute,
} as any)
const AppHabitsRoute = AppHabitsRouteImport.update({
  id: '/habits',
  path: '/habits',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunitiesIndexRoute = AppCommunitiesIndexRouteImport.update({
  id: '/communities/',
  path: '/communities/',
  getParentRoute: () => AppRoute,
} as any)
const AppChallengesIndexRoute = AppChallengesIndexRouteImport.update({
  id: '/challenges/',
  path: '/challenges/',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunitiesNewRoute = AppCommunitiesNewRouteImport.update({
  id: '/communities/new',
  path: '/communities/new',
  getParentRoute: () => AppRoute,
} as any)
const AppCommunitiesSlugRoute = AppCommunitiesSlugRouteImport.update({
  id: '/communities/$slug',
  path: '/communities/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppChallengesNewRoute = AppChallengesNewRouteImport.update({
  id: '/challenges/new',
  path: '/challenges/new',
  getParentRoute: () => AppRoute,
} as any)
const AppChallengesIdRoute = AppChallengesIdRouteImport.update({
  id: '/challenges/$id',
  path: '/challenges/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/habits': typeof AppHabitsRoute
  '/journal': typeof AppJournalRoute
  '/moderation': typeof AppModerationRoute
  '/partners': typeof AppPartnersRoute
  '/planner': typeof AppPlannerRoute
  '/profile': typeof AppProfileRoute
  '/tasks': typeof AppTasksRoute
  '/challenges/$id': typeof AppChallengesIdRoute
  '/challenges/new': typeof AppChallengesNewRoute
  '/communities/$slug': typeof AppCommunitiesSlugRoute
  '/communities/new': typeof AppCommunitiesNewRoute
  '/challenges/': typeof AppChallengesIndexRoute
  '/communities/': typeof AppCommunitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/analytics': typeof AppAnalyticsRoute
  '/dashboard': typeof AppDashboardRoute
  '/habits': typeof AppHabitsRoute
  '/journal': typeof AppJournalRoute
  '/moderation': typeof AppModerationRoute
  '/partners': typeof AppPartnersRoute
  '/planner': typeof AppPlannerRoute
  '/profile': typeof AppProfileRoute
  '/tasks': typeof AppTasksRoute
  '/challenges/$id': typeof AppChallengesIdRoute
  '/challenges/new': typeof AppChallengesNewRoute
  '/communities/$slug': typeof AppCommunitiesSlugRoute
  '/communities/new': typeof AppCommunitiesNewRoute
  '/challenges': typeof AppChallengesIndexRoute
  '/communities': typeof AppCommunitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/habits': typeof AppHabitsRoute
  '/_app/journal': typeof AppJournalRoute
  '/_app/moderation': typeof AppModerationRoute
  '/_app/partners': typeof AppPartnersRoute
  '/_app/planner': typeof AppPlannerRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/challenges/$id': typeof AppChallengesIdRoute
  '/_app/challenges/new': typeof AppChallengesNewRoute
  '/_app/communities/$slug': typeof AppCommunitiesSlugRoute
  '/_app/communities/new': typeof AppCommunitiesNewRoute
  '/_app/challenges/': typeof AppChallengesIndexRoute
  '/_app/communities/': typeof AppCommunitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/analytics'
    | '/dashboard'
    | '/habits'
    | '/journal'
    | '/moderation'
    | '/partners'
    | '/planner'
    | '/profile'
    | '/tasks'
    | '/challenges/$id'
    | '/challenges/new'
    | '/communities/$slug'
    | '/communities/new'
    | '/challenges/'
    | '/communities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/analytics'
    | '/dashboard'
    | '/habits'
    | '/journal'
    | '/moderation'
    | '/partners'
    | '/planner'
    | '/profile'
    | '/tasks'
    | '/challenges/$id'
    | '/challenges/new'
    | '/communities/$slug'
    | '/communities/new'
    | '/challenges'
    | '/communities'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/auth'
    | '/_app/analytics'
    | '/_app/dashboard'
    | '/_app/habits'
    | '/_app/journal'
    | '/_app/moderation'
    | '/_app/partners'
    | '/_app/planner'
    | '/_app/profile'
    | '/_app/tasks'
    | '/_app/challenges/$id'
    | '/_app/challenges/new'
    | '/_app/communities/$slug'
    | '/_app/communities/new'
    | '/_app/challenges/'
    | '/_app/communities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/planner': {
      id: '/_app/planner'
      path: '/planner'
      fullPath: '/planner'
      preLoaderRoute: typeof AppPlannerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/partners': {
      id: '/_app/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AppPartnersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/moderation': {
      id: '/_app/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof AppModerationRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/journal': {
      id: '/_app/journal'
      path: '/journal'
      fullPath: '/journal'
      preLoaderRoute: typeof AppJournalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/habits': {
      id: '/_app/habits'
      path: '/habits'
      fullPath: '/habits'
      preLoaderRoute: typeof AppHabitsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communities/': {
      id: '/_app/communities/'
      path: '/communities'
      fullPath: '/communities/'
      preLoaderRoute: typeof AppCommunitiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challenges/': {
      id: '/_app/challenges/'
      path: '/challenges'
      fullPath: '/challenges/'
      preLoaderRoute: typeof AppChallengesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communities/new': {
      id: '/_app/communities/new'
      path: '/communities/new'
      fullPath: '/communities/new'
      preLoaderRoute: typeof AppCommunitiesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/communities/$slug': {
      id: '/_app/communities/$slug'
      path: '/communities/$slug'
      fullPath: '/communities/$slug'
      preLoaderRoute: typeof AppCommunitiesSlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challenges/new': {
      id: '/_app/challenges/new'
      path: '/challenges/new'
      fullPath: '/challenges/new'
      preLoaderRoute: typeof AppChallengesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/challenges/$id': {
      id: '/_app/challenges/$id'
      path: '/challenges/$id'
      fullPath: '/challenges/$id'
      preLoaderRoute: typeof AppChallengesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppHabitsRoute: typeof AppHabitsRoute
  AppJournalRoute: typeof AppJournalRoute
  AppModerationRoute: typeof AppModerationRoute
  AppPartnersRoute: typeof AppPartnersRoute
  AppPlannerRoute: typeof AppPlannerRoute
  AppProfileRoute: typeof AppProfileRoute
  AppTasksRoute: typeof AppTasksRoute
  AppChallengesIdRoute: typeof AppChallengesIdRoute
  AppChallengesNewRoute: typeof AppChallengesNewRoute
  AppCommunitiesSlugRoute: typeof AppCommunitiesSlugRoute
  AppCommunitiesNewRoute: typeof AppCommunitiesNewRoute
  AppChallengesIndexRoute: typeof AppChallengesIndexRoute
  AppCommunitiesIndexRoute: typeof AppCommunitiesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppHabitsRoute: AppHabitsRoute,
  AppJournalRoute: AppJournalRoute,
  AppModerationRoute: AppModerationRoute,
  AppPartnersRoute: AppPartnersRoute,
  AppPlannerRoute: AppPlannerRoute,
  AppProfileRoute: AppProfileRoute,
  AppTasksRoute: AppTasksRoute,
  AppChallengesIdRoute: AppChallengesIdRoute,
  AppChallengesNewRoute: AppChallengesNewRoute,
  AppCommunitiesSlugRoute: AppCommunitiesSlugRoute,
  AppCommunitiesNewRoute: AppCommunitiesNewRoute,
  AppChallengesIndexRoute: AppChallengesIndexRoute,
  AppCommunitiesIndexRoute: AppCommunitiesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
